export const IS_LOADING = 'IS_LOADING';
export const SET_USER = 'SET_USER';

// post
export const SET_ALL_POST = 'SET_ALL_POST';
export const SET_LIKE_DISLIKE = 'SET_LIKE_DISLIKE';
export const SET_LIKED_USER_LIST = 'SET_LIKED_USER_LIST';
export const UPDATE_POST_LIST = 'UPDATE_POST_LIST';
export const SET_ACTIVE_POST = 'SET_ACTIVE_POST';
export const SET_ACTIVE_POST_COMMENTS = 'SET_ACTIVE_POST_COMMENTS';
export const SET_LIKE_COMMENTS = 'SET_LIKE_COMMENTS';
export const SET_REPLIES_COMMENTS = 'SET_REPLIES_COMMENTS';

//indian
export const SET_ALL_INDIANS = 'SET_ALL_INDIANS';
export const SET_ALL_PAGES = 'SET_ALL_PAGES';
export const SET_POST_CONNECT = 'SET_POST_CONNECT';
export const SET_POST_DISCONNECT = 'SET_POST_DISCONNECT';
export const SET_POST_CANCEL_REQUEST = 'SET_POST_CANCEL_REQUEST';

//pages
export const SET_POST_PAGES_CONNECT = 'SET_POST_PAGES_CONNECT';
export const SET_POST_PAGES_DISCONNECT = 'SET_POST_PAGES_DISCONNECT';
export const SET_ALL_PAGE_POST = 'SET_ALL_PAGE_POST';
export const SET_ALL_PAGE_FOLLOWER = 'SET_ALL_PAGE_FOLLOWER';
export const MY_PAGES = 'MY_PAGES'


export const SET_BLOCK_USER_LIST = 'SET_BLOCK_USER_LIST';
export const UPDATE_BLOCK_LIST = 'UPDATE_BLOCK_LIST';
export const OTHER_USER_INFO = 'OTHER_USER_INFO';
export const SET_OTHER_POST_LIST = 'SET_OTHER_POST_LIST';
export const SET_OTHER_USER_FOLLOWLIST = 'SET_OTHER_USER_FOLLOWLIST';

export const SET_GLOBAL_SEARCH = 'SET_GLOBAL_SEARCH';
export const SET_FOLLOWER_LIST = 'SET_FOLLOWER_LIST';

// discussion
export const SET_COUNTRY_DISCUSSION_LIST = 'SET_COUNTRY_DISCUSSION_LIST';
export const SET_THREAD_LIST = 'SET_THREAD_LIST';
export const UPDATE_COUNTRY_DISCUSSION_LIST = 'UPDATE_COUNTRY_DISCUSSION_LIST';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_MAIN_FOLLOWER_LIST = 'SET_MAIN_FOLLOWER_LIST';
// export const SET_FOLLOWER_LIST = 'SET_FOLLOWER_LIST'
// export const SET_FOLLOWER_LIST = 'SET_FOLLOWER_LIST'

// chat
export const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
