export const IS_LOADING = 'IS_LOADING';
export const SET_USER = 'SET_USER';

// post
export const SET_ALL_POST = 'SET_ALL_POST';
export const SET_LIKE_DISLIKE = 'SET_LIKE_DISLIKE';
export const SET_LIKED_USER_LIST = 'SET_LIKED_USER_LIST';
export const UPDATE_POST_LIST = 'UPDATE_POST_LIST';
export const SET_ACTIVE_POST = 'SET_ACTIVE_POST';
export const SET_ACTIVE_POST_COMMENTS = 'SET_ACTIVE_POST_COMMENTS';
export const SET_LIKE_COMMENTS = 'SET_LIKE_COMMENTS';
export const SET_REPLIES_COMMENTS = 'SET_REPLIES_COMMENTS';



//indian
export const SET_ALL_INDIANS = 'SET_ALL_INDIANS';
export const SET_ALL_PAGES = 'SET_ALL_PAGES';
export const SET_POST_CONNECT = 'SET_POST_CONNECT';
export const SET_POST_DISCONNECT = 'SET_POST_DISCONNECT';
export const SET_POST_CANCEL_REQUEST = 'SET_POST_CANCEL_REQUEST';

//pages
export const SET_POST_PAGES_CONNECT = 'SET_POST_PAGES_CONNECT';
export const SET_POST_PAGES_DISCONNECT = 'SET_POST_PAGES_DISCONNECT';
export const SET_ALL_PAGE_POST = 'SET_ALL_PAGE_POST';
export const SET_ALL_PAGE_FOLLOWER = 'SET_ALL_PAGE_FOLLOWER';
export const MY_PAGES = 'MY_PAGES'


export const SET_BLOCK_USER_LIST = 'SET_BLOCK_USER_LIST';
export const UPDATE_BLOCK_LIST = 'UPDATE_BLOCK_LIST';
export const OTHER_USER_INFO = 'OTHER_USER_INFO';
export const SET_OTHER_POST_LIST = 'SET_OTHER_POST_LIST';
export const SET_OTHER_USER_FOLLOWLIST = 'SET_OTHER_USER_FOLLOWLIST';

export const SET_GLOBAL_SEARCH = 'SET_GLOBAL_SEARCH';
export const SET_FOLLOWER_LIST = 'SET_FOLLOWER_LIST';

// discussion
export const SET_COUNTRY_DISCUSSION_LIST = 'SET_COUNTRY_DISCUSSION_LIST';
export const SET_THREAD_LIST = 'SET_THREAD_LIST';
export const UPDATE_COUNTRY_DISCUSSION_LIST = 'UPDATE_COUNTRY_DISCUSSION_LIST';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_MAIN_FOLLOWER_LIST = 'SET_MAIN_FOLLOWER_LIST';
// export const SET_FOLLOWER_LIST = 'SET_FOLLOWER_LIST'
// export const SET_FOLLOWER_LIST = 'SET_FOLLOWER_LIST'

// chat
export const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const SET_ACTIVE_CHAT_ROOM_USER = 'SET_ACTIVE_CHAT_ROOM_USER';
export const GET_GROUP_ROOMS = 'GET_GROUP_ROOMS';
export const SET_UNREAD_MSG_COUNT = 'SET_UNREAD_MSG_COUNT';
export const ADD_ONE_MESSAGE = 'ADD_ONE_MESSAGE';
export const SET_CHAT_DETAIL = 'SET_CHAT_DETAIL';
export const SET_CHAT_MEDIA_LINK = 'SET_CHAT_MEDIA_LINK';
export const SET_GROUP_CREATE_USERS = 'SET_GROUP_CREATE_USERS';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const SET_MY_PAGE_CHAT_USERS = 'SET_MY_PAGE_CHAT_USERS';
// export const GET_GROUP_ROOMS = 'GET_GROUP_ROOMS';


export const SET_NOTIFICATION_LIST = 'SET_NOTIFICATION_LIST';
export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';
// export const GET_GROUP_ROOMS = 'GET_GROUP_ROOMS';


// event
export const SET_ALL_EVENTS = 'SET_ALL_EVENTS';
export const SET_ACTIVE_EVENT = 'SET_ACTIVE_EVENT';
export const GET_SAVE_EVENT = 'GET_SAVE_EVENT';

export const SET_PAGE_CONNECT_POST = 'SET_PAGE_CONNECT_POST'
export const SET_PAGE_DETAIL = 'SET_PAGE_DETAIL';

export const GET_ALL_CURRENCIES = 'GET_ALL_CURRENCIES';

