export const Icons = {
  bell: require('../assets/Icons/bell.png'),
  search: require('../assets/Icons/search.png'),
  user: require('../assets/Icons/user.png'),
  logo: require('../assets/Icons/logo.png'),
  homeIcon: require('../assets/Icons/homeIcon.png'),
  peopleIcon: require('../assets/Icons/peopleIcon.png'),
  discussionIcon: require('../assets/Icons/peopleIcon.png'),
  chatIcon: require('../assets/Icons/chatIcon.png'),
  profileIcon: require('../assets/Icons/account_circle.png'),
  userImage: require('../assets/Icons/userImage.png'),
  Arrow_circle_right: require('../assets/Icons/Arrow_circle_right.png'),
  plusHome: require('../assets/Icons/plusHome.png'),
  menus: require('../assets/Icons/menus.png'),
  left_arrow: require('../assets/Icons/left-arrow.png'),
  more: require('../assets/Icons/more.png'),
  messageIcon: require('../assets/Icons/chatIcon.png'),
  postViewImage: require('../assets/Icons/postViewImage.png'),
  heart: require('../assets/Icons/heart.png'),
  chatCircle: require('../assets/Icons/chatCircle.png'),
  share: require('../assets/Icons/share.png'),
  dotMenu: require('../assets/Icons/dotMenu.png'),
  photoUpload: require('../assets/Icons/photoUpload.png'),
  videoUpload: require('../assets/Icons/videoUpload.png'),
  heartFilled: require('../assets/Icons/heartFilled.png'),
  replyIcon: require('../assets/Icons/replyIcon.png'),
  send: require('../assets/Icons/send.png'),
  setting: require('../assets/Icons/setting.png'),
  penEdit: require('../assets/Icons/penEdit.png'),
  userChat: require('../assets/Icons/userChat.png'),
  connect: require('../assets/Icons/connect.png'),
  trash: require('../assets/Icons/trash.png'),
  addImage: require('../assets/Icons/addImage.png'),
  checkbox: require('../assets/Icons/checkbox.png'),
  checkbox1: require('../assets/Icons/checkbox1.png'),
  contact: require('../assets/Icons/contact.png'),
  postAdd: require('../assets/Icons/postAdd.png'),
  addImage1: require('../assets/Icons/addImages.png'),

  personAdd: require('../assets/Icons/personAdd.png'),
  play: require('../assets/Icons/play.png'),
  image: require('../assets/Icons/image.png'),
  more1: require('../assets/Icons/more1.png'),
  DiscussionOff: require('../assets/Icons/DiscussionOff.png'),
  Discussion: require('../assets/Icons/Discussion.png'),
  account: require('../assets/Icons/account.png'),
  peopleIcon1: require('../assets/Icons/peopleIcon1.png'),
  check: require('../assets/Icons/check.png'),
  sent: require('../assets/Icons/sent.png'),
  close: require('../assets/Icons/close.png'),
  down_arrow: require('../assets/Icons/down_arrow.png'),
  closeRound: require('../assets/Icons/closeRound.png'),
  loginBg: require('../assets/Icons/loginBg.png'),
  hide: require('../assets/Icons/hide.png'),
  view: require('../assets/Icons/view.png'),
  googlePlus: require('../assets/Icons/googlePlus.png'),

  maleGender: require('../assets/Icons/maleGender.png'),
  femenine: require('../assets/Icons/femenine.png'),
  star: require('../assets/Icons/star.png'),
  camera: require('../assets/Icons/camera.png'),
  calender: require('../assets/Icons/calender.png'),
  Verified_user: require('../assets/Icons/Verified_user.png'),
  checkCircle: require('../assets/Icons/checkCircle.png'),
  plus: require('../assets/Icons/plus.png'),
  addphoto: require('../assets/Icons/addphoto.png'),
  plusPost: require('../assets/Icons/plusPost.png'),
  imagelist: require('../assets/Icons/imagelist.png'),
  users: require('../assets/Icons/users.png'),
  files: require('../assets/Icons/files.png'),
  starOutline: require('../assets/Icons/starOutline.png'),
  favorite: require('../assets/Icons/favorite.png'),
  checkSquare: require('../assets/Icons/checkSquare.png'),
  group: require('../assets/Icons/group.png'),
  clock: require('../assets/Icons/clock.png'),
  calenderDate: require('../assets/Icons/calenderDate.png'),
  map: require('../assets/Icons/map.png'),
  tickets: require('../assets/Icons/tickets.png'),
  contacts: require('../assets/Icons/contacts.png'),
  add: require('../assets/Icons/add.png'),
  minus: require('../assets/Icons/minus.png'),
  edit: require('../assets/Icons/edit.png'),
  editEvent: require('../assets/Icons/editEvent.png'),
  megaphone: require('../assets/Icons/megaphone.png'),
  checkRound: require('../assets/Icons/checkRound.png'),
  playVideo: require('../assets/Icons/playVideo.png'),
  blockUser: require('../assets/Icons/blockUser.png'),
  block: require('../assets/Icons/block.png'),
  report: require('../assets/Icons/report.png'),
  logout: require('../assets/Icons/logout.png'),
  pdf: require('../assets/Icons/pdf.png'),
  // files: require('../assets/Icons/files.png'),
  // files: require('../assets/Icons/files.png'),
  // files: require('../assets/Icons/files.png'),



  w_1: require('../assets/Icons/w_1.png'),
  w_2: require('../assets/Icons/w_2.png'),
  w_3: require('../assets/Icons/w_3.png'),
  w_4: require('../assets/Icons/w_4.png'),
  w_5: require('../assets/Icons/w_5.png'),
  w_6: require('../assets/Icons/w_6.png'),
  w_7: require('../assets/Icons/w_7.png'),
};
