export const Icons = {
    bell: require('../assets/Icons/bell.png'),
    search: require('../assets/Icons/search.png'),
    user: require('../assets/Icons/user.png'),
    logo: require('../assets/Icons/logo.png'),
    homeIcon: require('../assets/Icons/homeIcon.png'),
    peopleIcon: require('../assets/Icons/peopleIcon.png'),
    discussionIcon: require('../assets/Icons/peopleIcon.png'),
    chatIcon: require('../assets/Icons/chatIcon.png'),
    profileIcon: require('../assets/Icons/chatIcon.png'),
    userImage: require('../assets/Icons/userImage.png'),
    Arrow_circle_right: require('../assets/Icons/Arrow_circle_right.png'),
    plusHome: require('../assets/Icons/plusHome.png'),
    menus: require('../assets/Icons/menus.png'),
    // logo: require('../assets/Icons/logo.png'),
    // logo: require('../assets/Icons/logo.png'),
    // logo: require('../assets/Icons/logo.png'),
    // logo: require('../assets/Icons/logo.png'),

}  