import {Image, StyleSheet, Text, View} from 'react-native';
import React from 'react';
import colors from '../Themes/Colors';
import {wp} from '../Themes/Fonts';
import {FontStyle, ImageStyle} from '../utils/commonFunction';
import {Icons} from '../Themes/Icons';
import moment from 'moment';

export default function RenderEventTicket({item}) {
  return (
    <View>
      <View style={styles.topView}>
        <View style={styles.innerView}>
          <View style={styles.middleView}>
            <Image source={Icons.logo} style={ImageStyle(32, 32)} />
            <Text style={[styles.titleText]}>{' IndiansAbroad'}</Text>
          </View>
          <Text style={styles.titleTextEvent}>Event Ticket</Text>
          <View style={styles.blueView}>
            <Text style={{...FontStyle(15, colors.white, '700')}}>
              {item?.title}
            </Text>
            <Text style={{...FontStyle(12, colors.white, '700')}}>
              By {item?.page_owner}
            </Text>
            <Text style={{...FontStyle(12, colors.white), marginTop: 10}}>
              {item?.address}, {moment(item?.start_time).format('MM/DD/YYYY')}
            </Text>
            <Text style={{...FontStyle(12, colors.white)}}>
              Starts at : {moment(item.start_time).format('HH:MM')}
            </Text>
            {/* <Text style={{...FontStyle(12, colors.white)}}>
              Confirmation Number: 4598734
            </Text> */}
          </View>
          <Image
            source={{uri:item?.ticket}}
            style={styles.qrImage}
          />
          <View style={styles.bottomLine}>
            <Text
              style={{
                ...FontStyle(14, colors.neutral_900, '700'),
                textAlign: 'center',
              }}>
              Ticket generated by IndiansAbroad app
            </Text>
          </View>
        </View>
      </View>
      <View>
        <Text style={styles.bottomText}>
          Explore more events with IndiansAbroad and enjoy
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  topView: {
    backgroundColor: colors.secondary_500,
    padding: wp(16),
  },
  innerView: {
    backgroundColor: colors.white,
    borderRadius: 50,
    padding: wp(26),
  },
  middleView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral_800,
    paddingBottom: 5,
  },
  titleText: {
    ...FontStyle(20, colors.neutral_900, '700'),
  },
  titleTextEvent: {
    ...FontStyle(32, colors.neutral_900, '700'),
    textAlign: 'center',
    paddingVertical: 20,
  },
  blueView: {
    backgroundColor: colors.primary_500,
    padding: 5,
  },
  qrImage: {
    width: 230,
    height: 230,
    alignSelf: 'center',
    marginVertical: 20,
  },
  bottomLine: {
    borderTopWidth: 1,
    borderTopColor: colors.neutral_800,
    paddingTop: 10,
  },
  bottomText: {
    ...FontStyle(14, colors.primary_500, '700'),
    textAlign: 'center',
    padding: 5,
  },
});
