-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU7ZqfXpVHlivJwKO
HBXhW4C6/SOgtCrT25t+btTDe3GgCgYIKoZIzj0DAQehRANCAAQOJOQ7iMbaVT1i
42DNFdQMIVFs9vRxnDmfNF6Ci04A6PINImdRwszX8FsTvrTeWk3RajKlUSf/voiI
G+hxwLBI
-----END PRIVATE KEY-----